name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Run tests
        run: make test

  valgrind:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build
        run: make build

      - name: Valgrind
        run: make valgrind

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -y gcovr
      - name: Run coverage
        run: make coverage
      - name: Coverage report
        run: |
          gcovr --root . --filter src/ --txt